### ISSUE TITLE
tx.encode and tx.decode error

### ISSUE THREAD

**Issue by SalletOne** [terra-money/terra.py#100]
- terra_sdk version:  github branch main 
- Python version: 3.8
- Operating System: windows 7

### Description

terra = LCDClient(chain_id="bombay-12", url="https://bombay-lcd.terra.dev/")

seed = "words"
key = MnemonicKey(mnemonic=seed)

msg = MsgSend(
	key.acc_address,
	"terra1uv5acl0xnckxd76s630h5erm8l8nuw9hq6gr2s",
	Coins(uluna=200000),
)

tx_opt = CreateTxOptions(
			msgs=[msg],
			fee=Fee(200000, "120000uluna"),
			memo="",
			gas_adjustment=1.5,
			fee_denoms = ["uluna"]
		)
signer_opt = SignerOptions(address=key.acc_address)

acc_info = terra.auth.account_info(key.acc_address)

sign_opt = SignOptions(
	account_number=acc_info.account_number,
	sequence=acc_info.sequence,
	sign_mode=SignMode.SIGN_MODE_DIRECT,
	chain_id="bombay-12",
)

tx = terra.tx.create([signer_opt], tx_opt)
signed_tx = key.sign_tx(tx, sign_opt)

print("=" * 64)
# encode
encoded = terra.tx.encode(signed_tx)
print(encoded)

print("=" * 64)
# decode
decoded = terra.tx.decode(encoded)
print(decoded)

# when i encode again, error occur
encoded_again = terra.tx.encode(decoded)
print(encoded_again)

### What I Did

```
Traceback (most recent call last):
  File "D:\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\workspace-py\terra.py\venv\lib\site-packages\nest_asyncio.py", line 127, in manage_run
    yield
  File "D:\workspace-py\terra.py\venv\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "D:\Python38\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "D:\Python38\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "D:\workspace-py\terra.py\terra_sdk\client\lcd\api\tx.py", line 242, in encode
    return base64.b64encode(tx.to_proto().SerializeToString()).decode()
  File "D:\workspace-py\terra.py\terra_sdk\core\tx.py", line 79, in to_proto
    proto.body = self.body.to_proto()
  File "D:\workspace-py\terra.py\terra_sdk\core\tx.py", line 176, in to_proto
    messages=[m.pack_any() for m in self.messages],
  File "D:\workspace-py\terra.py\terra_sdk\core\tx.py", line 176, in <listcomp>
    messages=[m.pack_any() for m in self.messages],
  File "D:\workspace-py\terra.py\venv\lib\site-packages\betterproto\__init__.py", line 688, in __getattribute__
    value = super().__getattribute__(name)
AttributeError: 'MsgSend' object has no attribute 'pack_any'
```

**Comment by Aureliano90** [comment]
The issue comes down to `betterproto.Message.parse`. The message created by `from_proto` doesn't return the same type. As can be seen by
```
>>> og = signed_tx
>>> encoded = await terra.tx.encode(signed_tx)
>>> decoded = await terra.tx.decode(encoded)
>>> print(type(og.body) == type(decoded.body))
True
>>> print(type(og.body.messages[0]) == type(decoded.body.messages[0])
False
```

By the way @[Vritra4](https://github.com/Vritra4), I don't think defining `encode` and `decode` as async is necessary.
