### ISSUE TITLE
tx_info no longer working on Mainnet or Testnet post Columbus-5 update

### ISSUE THREAD

**Issue by realkibou** [terra-money/terra.py#28]
- terra_sdk version: 0.14.0
- Python version: 3.9.6
- Operating System: Win 10 64-bit 21H1

```
if config.NETWORK == 'MAINNET':
    chain_id = 'columbus-5'
    public_node_url = 'https://lcd.terra.dev'

else:
    chain_id = 'bombay-12'
    public_node_url = 'https://bombay-fcd.terra.dev'

terra = LCDClient(chain_id=chain_id, url=public_node_url)
```

Mainnet:
terra.tx.tx_info('42DE8348A333613EB013251DE2056EE301019DA8C2505935B24E8596AFD350A1')

Testnet:
terra.tx.tx_info('BC00BDD340F8622679A8746CC0AC3474D87D3189F4F7263A77C873D3A3D9ED17')

Both return the same error_
```
Traceback (most recent call last):
  File "C:\_Code\Terra One-Stop-Bot\C_Main.py", line 1744, in <module>
    print(terra.tx.tx_info('BC00BDD340F8622679A8746CC0AC3474D87D3189F4F7263A77C873D3A3D9ED17'))
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\wrapt\wrappers.py", line 605, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\tx.py", line 28, in tx_info
    return TxInfo.from_data(await self._c._get(f"/txs/{tx_hash}", raw=True))
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\core\auth\data\tx.py", line 276, in from_data
    parse_tx_logs(data.get("logs")),
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\core\auth\data\tx.py", line 196, in parse_tx_logs
    [
  File "C:\Users\mE\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\core\auth\data\tx.py", line 197, in <listcomp>
    TxLog(msg_index=log["msg_index"], log=log["log"], events=log["events"])
KeyError: 'msg_index'
```

**Comment by DanKorob** [comment]
Hi @realkibou, are you aware of upcoming PR for SDK with updates for Col-5? #20

**Comment by realkibou** [comment]
I wasn't, but how does this fix the issue?

**Comment by DanKorob** [comment]
I mean that the release branch (0.14.0) of terra-sdk-python doesn't support Col-5 yet.
Yes, you can install it using pip referring to git commit:
`$ pip3 install -U terra-sdk@git+https://github.com/terra-money/terra-sdk-python.git@32f65fd08c2c3aa707b0f5242230b5ec8ac9b884`

**Please, be aware that PR is still in progress and something may not work as you expect.**
