### ISSUE TITLE
Error during validators complete data fetch using SDK

### ISSUE THREAD

**Issue by Akpadhy** [terra-money/terra.py#35]
- terra_sdk version: 0.14.0
- Python version:3.8
- Operating System:mac os catalina

### Description

I am working on getting all data related to validators for a particular time.To do that I started. using terra sdk and also direct api call using python request.Python request is fine but wee are interested in using sdk feature.

### What I Did

I tried simple. sdk module and. call the validators as below however it failed with error and complete traceback is added:

```
from terra_sdk.client.lcd import LCDClient
client = LCDClient(chain_id="columbus-4", url="https://lcd.terra.dev")
validators = client.staking.validators()#client.staking.validators()#
print(validators)
```

Error traceback is as below:
```
Traceback (most recent call last):
  File "/Users/cloudusr/Documents/projects/stader-validators-data-etl-v0/etl/test.py", line 56, in <module>
    data_crawlers()
  File "/Users/cloudusr/Documents/projects/stader-validators-data-etl-v0/etl/test.py", line 38, in data_crawlers
    validators = client.staking.validators()#client.staking.validators()#
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/terra_sdk/client/lcd/api/staking.py", line 173, in validators
    return [Validator.from_data(d) for d in res]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/terra_sdk/client/lcd/api/staking.py", line 173, in <listcomp>
    return [Validator.from_data(d) for d in res]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/terra_sdk/core/staking/data/validator.py", line 142, in from_data
    jailed=data["jailed"],
KeyError: 'jailed'

Process finished with exit code 1

```

**Comment by Vritra4** [comment]
released as stable.

**Comment by Vritra4** [comment]
lcd is light client daemon running inside of core itself and it's only have col-5's data now. and they may pruning history of states. so if height in option is too low from latest, it won't work. 
fcd is fat client daemon and it resides outside of core. it contains older data.
