### ISSUE TITLE
Error Getting Validator Rewards

### ISSUE THREAD

**Issue by Michael-C-Dev** [terra-money/terra.py#37]
- terra_sdk version: terra-sdk-1.0.0
- Python version: 3.9
- Operating System: Windows 10

### Description
Attempting to query the available commissions acrued from a validator using the `distribution.validator_rewards(terraveloper)` function. Attempted this for multiple validators' terraveloper addresses but every time code errored.

### What I Did

Script
```
terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
print(terra.distribution.validator_rewards("terravaloper1259cmu5zyklsdkmgstxhwqpe0utfe5hhyty0at"))
```
Traceback:
```
Traceback (most recent call last):
  File "C:\Users\Micha\git_repos\comission\main.py", line 15, in <module>
    check_comission()
  File "C:\Users\Micha\git_repos\comission\main.py", line 9, in check_comission
    print(terra.distribution.validator_rewards("terravaloper1259cmu5zyklsdkmgstxhwqpe0utfe5hhyty0at"))
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\Micha\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\terra_sdk\client\lcd\api\distribution.py", line 61, in validator_rewards
    val_commission=Coins.from_data(res["val_commission"]),
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\terra_sdk\core\coins.py", line 114, in from_data
    return cls(coins)
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\terra_sdk\core\coins.py", line 80, in __init__
    for coin in coins:
  File "C:\Users\Micha\git_repos\comission\venv\lib\site-packages\terra_sdk\core\coin.py", line 213, in from_data
    return cls(data["denom"], data["amount"])
TypeError: string indices must be integers
```

**Comment by Vritra4** [comment]
it is fixed :) use 1.0.1 please.
