### ISSUE TITLE
supply.total()

### ISSUE THREAD

**Issue by JSilvermanCohen** [terra-money/terra.py#56]
- terra_sdk version: 1.0.2 (and same behavior on 1.0.0)
- Python version:  3.9.2
- Operating System: Windows 10 (and similar behavior on Ubuntu WSL on Windows)

### Description

I am trying to set-up getting information from Terra. I have imported terra_sdk and I am just trying to get some test set up.  I can run terra.node_info() and terra.block_info() for both `columbus-4` and `columbus-5` but `terra.supply.total()`  fails.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
>>> terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
>>> terra.supply.total()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jsilverman\AppData\Roaming\Python\Python39\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
  File "C:\Users\jsilverman\AppData\Roaming\Python\Python39\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
  File "C:\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\jsilverman\AppData\Roaming\Python\Python39\site-packages\terra_sdk\client\lcd\api\supply.py", line 15, in total
  File "C:\Users\jsilverman\AppData\Roaming\Python\Python39\site-packages\terra_sdk\client\lcd\lcdclient.py", line 243, in _get
  File "C:\Users\jsilverman\AppData\Roaming\Python\Python39\site-packages\terra_sdk\client\lcd\lcdclient.py", line 95, in _get
terra_sdk.exceptions.LCDResponseError: Status 501

**Comment by Vritra4** [comment]
sorry for your inconvenience. it will be fixed with v2.

**Comment by Vritra4** [comment]
v2.0.0 released
