### ISSUE TITLE
Calling StdFee in create_and_sign_tx returns error

### ISSUE THREAD

**Issue by tjpeterson94** [terra-money/terra.py#59]
terra_sdk version: 1.02
Python version: 3.9.2
Operating System: Windows 10

### Description
When calling create_and_sign_tx() using StdFee() to set fee rate I receive the following error message.  
`terra_sdk.exceptions.LCDResponseError: Status 400 - this transaction cannot be broadcasted via legacy REST endpoints, because it does not support Amino serialization. Please either use CLI, gRPC, gRPC-gateway, or directly query the Tendermint RPC endpoint to broadcast this transaction. The new REST endpoint (via gRPC-gateway) is POST /cosmos/tx/v1beta1/txs. Please also see the REST endpoints migration guide at https://docs.cosmos.network/master/migrations/rest.html for more info`
No issues when I set the fee through with gas_prices and gas_adjustment.

### What I Did
Broken function:
```
def execute_contract(msgs,gas_fee,gas_adjustment):
    tx=wallet.create_and_sign_tx(msgs=msgs
                                ,fee=fee=StdFee(1200000, '{}uusd'.format(round(fee * 1000000,0))
                                )
    result = terra.tx.broadcast(tx)
    print(f'RESULTS:{result}')
```

Working function:
```
def execute_contract(msgs,gas_fee,gas_adjustment):
    tx=wallet.create_and_sign_tx(msgs=msgs
                                ,gas_prices=gas_fee
                                ,gas_adjustment=gas_adjustment
                                )
    result = terra.tx.broadcast(tx)
    print(f'RESULTS:{result}')
```
 Full Traceback:
```
Traceback (most recent call last):
  File "C:\Users\19054\Desktop\terraswap_blunaluna\testing_stdfee.py", line 50, in <module>
    test = execute_trade(blunaluna_contract_astro,0.1,'uluna',wallet,terra,0.1)
  File "C:\Users\19054\Desktop\terraswap_blunaluna\testing_stdfee.py", line 42, in execute_trade
    execute_tx_result = terra.tx.broadcast(execute_tx)
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\tx.py", line 226, in broadcast
    res = await self._broadcast(tx, "block", options)
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\api\tx.py", line 178, in _broadcast
    return await self._c._post("/txs", data, raw=True)
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\lcdclient.py", line 255, in _post
    result = await super()._post(*args, **kwargs)
  File "C:\Users\19054\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\client\lcd\lcdclient.py", line 110, in _post
    raise LCDResponseError(message=result.get("error"), response=response)
terra_sdk.exceptions.LCDResponseError: Status 400 - this transaction cannot be broadcasted via legacy REST endpoints, because it does not support Amino serialization. Please either use CLI, gRPC, gRPC-gateway, or directly query the Tendermint RPC endpoint to broadcast this transaction. The new REST endpoint (via gRPC-gateway) is POST /cosmos/tx/v1beta1/txs. Please also see the REST endpoints migration guide at https://docs.cosmos.network/master/migrations/rest.html for more info
```

**Comment by Vritra4** [comment]
sorry for the delay! try again with v2.0.0
