### ISSUE TITLE
Error execution examples

### ISSUE THREAD

**Issue by roberanleo** [terra-money/terra.py#67]
- terra_sdk version: 
- Python version: 3.9
- Operating System: Windows

### Description

when execute:
from terra_sdk.client.lcd import LCDClient
from terra_sdk.key.mnemonic import MnemonicKey
from terra_sdk.core.auth import StdFee
from terra_sdk.core.bank import MsgSend

mk = MnemonicKey(mnemonic="MNEMONIC")
terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
wallet = terra.wallet(mk)

tx = wallet.create_and_sign_tx(
    msgs=[MsgSend(
        wallet.key.acc_address,
        "RECIPIENT",
        "1000000uluna" # send 1 luna
    )],
    memo="test transaction!",
    fee=StdFee(200000, "120000uluna")
)

result = terra.tx.broadcast(tx)
print(result)

### What I Did

Traceback (most recent call last):
  File "c:\python-virtual-environments\TestTerraFirst\WalletTerra2.py", line 11, in <module>
    tx = wallet.create_and_sign_tx(
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\wallet.py", line 137, in create_and_sign_tx
    self.create_tx(
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\wallet.py", line 93, in create_tx
    return self.lcd.tx.create(
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\api\tx.py", line 78, in create
    account = await BaseAsyncAPI._try_await(self._c.auth.account_info(sender))
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\client\lcd\api\auth.py", line 25, in account_info
    return Account.from_data(result)
  File "C:\python-virtual-environments\TestTerraFirst\lib\site-packages\terra_sdk\core\auth\data\account.py", line 48, in from_data
    address=data["address"],
KeyError: 'address'

**Comment by jfantell** [comment]
I am having the same issue

**Comment by Vritra4** [comment]
check your mnemonic and address please.

**Comment by jfantell** [comment]
I was able to get past this issue by instantiating the LCDClient with the URL `https://bombay-lcd.terra.dev` as opposed to `https://lcd.terra.dev`.

Also, @Vritra4 I kindly ask that you do not assume an issue is closed until you (or someone else) follow up with the individual(s) who filed/experienced the issue. It is bad practice to do otherwise and you run the risk your assumption is wrong (as it was this time).
