### ISSUE TITLE
parse_msg() KeyError: '/cosmos.authz.v1beta1.MsgExec'

### ISSUE THREAD

**Issue by nerewarin** [terra-money/terra.py#83]
- terra_sdk version: 2.0.4
- Python version: 3.8
- Operating System: both Win10 or Docker Compose setup

### Description

cannot fetch tx_info - KeyError: '/cosmos.authz.v1beta1.MsgExec'
seems like at least this proto class is missed in parse_msg

### What I Did

```
from terra_sdk.client.lcd import LCDClient

terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
terra.tx.tx_info('da66fac2c941d3862f743ceac2b343ff47348883e894c00506cdc58a202a5b81')

```
PyCharm output:
```
G:\PycharmProjects\cryptology\tera\venv\Scripts\python.exe G:/PycharmProjects/cryptology/tera/tera/fetch_transactions_keyerror.py
Traceback (most recent call last):
  File "G:/PycharmProjects/cryptology/tera/tera/fetch_transactions_keyerror.py", line 4, in <module>
    terra.tx.tx_info('da66fac2c941d3862f743ceac2b343ff47348883e894c00506cdc58a202a5b81')
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\client\lcd\api\_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Python38\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Python38\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\client\lcd\api\tx.py", line 132, in tx_info
    return TxInfo.from_data(res["tx_response"])
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\core\tx.py", line 441, in from_data
    Tx.from_data(data['tx']),
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\core\tx.py", line 83, in from_data
    TxBody.from_data(data["body"]),
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\core\tx.py", line 177, in from_data
    [Msg.from_data(m) for m in data["messages"]],
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\core\tx.py", line 177, in <listcomp>
    [Msg.from_data(m) for m in data["messages"]],
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\core\msg.py", line 21, in from_data
    return parse_msg(data)
  File "G:\PycharmProjects\cryptology\tera\venv\lib\site-packages\terra_sdk\util\base.py", line 27, in from_data
    return table[data["@type"]](data)
KeyError: '/cosmos.authz.v1beta1.MsgExec'
```

**Comment by Vritra4** [comment]
thanks for reporting! actually it is fixed in feature/decode branch but not released.
it will be released soon with some other fixes.

**Comment by Vritra4** [comment]
2.0.5 is out now :)

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)
