### ISSUE TITLE
create_and_sign_tx - AttributeError: 'BlockTxBroadcastResult' object has no attribute 'encode'

### ISSUE THREAD

**Issue by spaceh3ad** [terra-money/terra.py#84]
- terra_sdk version: 2.0.4
- Python version: 3.9.7
- Operating System: Ubuntu 20.04

### Description

I am trying to deploy cw20 token to Local Terra, but when executing contract I get attribute error.

### What I Did

```
from terra_sdk.client.lcd.api.tx import CreateTxOptions
from terra_sdk.client.localterra import LocalTerra
from terra_sdk.util.contract import get_code_id, read_file_as_b64
from terra_sdk.core.wasm import MsgStoreCode, MsgInstantiateContract, MsgExecuteContract
from terra_sdk.core.coins import Coins
from terra_sdk.core.fee import Fee

lt = LocalTerra()
deployer = lt.wallets["test1"]
test_acc = lt.wallets["test2"]


def store_contract(contract_name):
    contract_bytes = read_file_as_b64(f"artifacts/{contract_name}.wasm")
    store_code = MsgStoreCode(deployer.key.acc_address, contract_bytes)
    tx = deployer.create_and_sign_tx(CreateTxOptions(
        msgs=[store_code]
    ))
    result = lt.tx.broadcast(tx)
    code_id = get_code_id(result)
    return code_id


def instantiate_contract(code_id: str, init_msg: dict) -> str:
    instantiate = MsgInstantiateContract(
        sender=deployer.key.acc_address,
        admin=deployer.key.acc_address,
        code_id=code_id,
        init_msg=init_msg,
    )

    tx = deployer.create_and_sign_tx(CreateTxOptions(
        msgs=[instantiate]
    ))

    result = lt.tx.broadcast(tx)
    print(result)
    return result


def execute_contract(sender, contract_addr: str, execute_msg):

    execute = MsgExecuteContract(
        sender=sender.key.acc_address, contract=contract_addr, execute_msg=execute_msg
    )
    # tx = sender.create_and_sign_tx(CreateTxOptions(
    #     msgs=[execute],
    #     fee=Fee(1000000, "1000000uluna")
    # ))
    execute = MsgExecuteContract(
        sender.key.acc_address,
        contract_addr,
        execute_msg,
        {"uluna": 100000},
    )

    execute_tx = sender.create_and_sign_tx(
        CreateTxOptions(msgs=[execute], fee=Fee(1000000, Coins(uluna=1000000)))
    )

    result = lt.tx.broadcast(execute_tx)
    print(result)
    return result


code_id = store_contract("terraswap_token")
contract_address = instantiate_contract(code_id,
                                        {
                                            "name": "Test Terra Token",
                                            "symbol": "TTT",
                                            "decimals": 6,
                                            "initial_balances": [
                                                {"address": deployer.key.acc_address,
                                                    "amount": "1000000000"}
                                            ]
                                        })

execute_contract(deployer, contract_address, {
    "transfer": {
        "recipient": test_acc.key.acc_address,
        "amount": "50000000000"
    }
})

print(lt.wasm.contract_query(contract_address, {
      "balance": {"address": deployer.key.acc_address}}))

print(lt.wasm.contract_query(contract_address, {
      "balance": {"address": test_acc.key.acc_address}}))

```

**Comment by Vritra4** [comment]
What was the error?

**Comment by spaceh3ad** [comment]
```
(base) josh@jmachine:~/Matrix/Code/BlockchainDev/Rust/terra-contract-tubbly$ python deploy_contract.py 
BlockTxBroadcastResult(height=35, txhash='07237D239DC291125BE1316E61B054A1A06D5AB4651E3B6269966CFEC862A1D6', raw_log='[{"events":[{"type":"instantiate_contract","attributes":[{"key":"creator","value":"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"},{"key":"admin","value":"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"},{"key":"code_id","value":"1"},{"key":"contract_address","value":"terra18vd8fpwxzck93qlwghaj6arh4p7c5n896xzem5"}]},{"type":"message","attributes":[{"key":"action","value":"/terra.wasm.v1beta1.MsgInstantiateContract"},{"key":"module","value":"wasm"},{"key":"sender","value":"terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"}]}]}]', gas_wanted=486255, gas_used=290963, logs=[TxLog(msg_index=0, log='', events=[{'type': 'instantiate_contract', 'attributes': [{'key': 'creator', 'value': 'terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v'}, {'key': 'admin', 'value': 'terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v'}, {'key': 'code_id', 'value': '1'}, {'key': 'contract_address', 'value': 'terra18vd8fpwxzck93qlwghaj6arh4p7c5n896xzem5'}]}, {'type': 'message', 'attributes': [{'key': 'action', 'value': '/terra.wasm.v1beta1.MsgInstantiateContract'}, {'key': 'module', 'value': 'wasm'}, {'key': 'sender', 'value': 'terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v'}]}], events_by_type={'instantiate_contract': {'creator': ['terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v'], 'admin': ['terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v'], 'code_id': ['1'], 'contract_address': ['terra18vd8fpwxzck93qlwghaj6arh4p7c5n896xzem5']}, 'message': {'action': ['/terra.wasm.v1beta1.MsgInstantiateContract'], 'module': ['wasm'], 'sender': ['terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v']}})], code=0, codespace='', info=None, data=None, timestamp=None)
Traceback (most recent call last):
  File "/home/josh/Matrix/Code/BlockchainDev/Rust/terra-contract-tubbly/deploy_contract.py", line 78, in <module>
    execute_contract(deployer, contract_address, {
  File "/home/josh/Matrix/Code/BlockchainDev/Rust/terra-contract-tubbly/deploy_contract.py", line 57, in execute_contract
    execute_tx = sender.create_and_sign_tx(
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/client/lcd/wallet.py", line 130, in create_and_sign_tx
    return self.key.sign_tx(
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/key/key.py", line 226, in sign_tx
    signature: SignatureV2 = self.create_signature(signDoc)
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/key/key.py", line 183, in create_signature
    signature = self.sign(sign_doc.to_bytes())
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/core/sign_doc.py", line 78, in to_bytes
    return bytes(self.to_proto())
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/core/sign_doc.py", line 71, in to_proto
    body_bytes=bytes(self.tx_body.to_proto()),
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/core/tx.py", line 175, in to_proto
    messages=[m.pack_any() for m in self.messages],
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/core/tx.py", line 175, in <listcomp>
    messages=[m.pack_any() for m in self.messages],
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/core/msg.py", line 13, in pack_any
    return Any_pb(type_url=self.type_url, value=bytes(self.to_proto()))
  File "/home/josh/miniconda3/lib/python3.9/site-packages/betterproto/__init__.py", line 815, in __bytes__
    output += _serialize_single(
  File "/home/josh/miniconda3/lib/python3.9/site-packages/betterproto/__init__.py", line 396, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
  File "/home/josh/miniconda3/lib/python3.9/site-packages/betterproto/__init__.py", line 364, in _preprocess_single
    return value.encode("utf-8")
AttributeError: 'BlockTxBroadcastResult' object has no attribute 'encode'
```

**Comment by Vritra4** [comment]
your instantiate_contract() doesn't return contract_address.
you have to get contract address from result like https://github.com/terra-money/terra.py/blob/9fa0c386ae3aa7f748f9c72d6302257a8d556f66/integration_tests/contract.py#L47
